# Generated by Django 4.1.7 on 2023-07-16 12:42

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50, verbose_name='Категорія')),
                ('category_uk', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Категорія')),
                ('category_ru', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Категорія')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=50, verbose_name='Модель')),
                ('model_uk', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Модель')),
                ('model_ru', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Моделі',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.CharField(max_length=255, verbose_name='Назва')),
                ('parts_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('parts_ru', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True)),
                ('price', models.CharField(default='Ціну уточнюйте', max_length=20, verbose_name='Ціна')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Активне')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category')),
                ('model', models.ManyToManyField(to='main.model')),
            ],
            options={
                'verbose_name': 'Автозапчастину',
                'verbose_name_plural': 'Автозапчастини',
                'ordering': ['time_create', 'parts'],
            },
        ),
        migrations.CreateModel(
            name='PartsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.part_image_path)),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_images', to='main.parts')),
            ],
        ),
    ]
