# Generated by Django 4.1.7 on 2023-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alias', models.SlugField(max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='main/img/parts')),
                ('price', models.IntegerField(default='Ціну уточнюйте')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
