# Generated by Django 4.1.7 on 2023-04-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_partsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsimage',
            name='parts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_images', to='main.parts'),
        ),
    ]
