# Generated by Django 4.1.7 on 2023-04-22 13:24

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_partsimage_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='parts',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='partsimage',
            name='image',
            field=models.ImageField(upload_to=main.models.part_image_path),
        ),
    ]
